FROM python:3.10-slim AS builder

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.10-slim

# FIX: Force Python to print logs immediately (Unbuffered)
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

COPY app.py .

EXPOSE 8080

ENV FLASK_APP=app.py

CMD ["python3", "app.py"]