networks: # <--- 1. Define the network externally
  purple_network:
    external: true

services:
  ci_server:
    build:
      context: .
      dockerfile: dockerfile

    restart: always

    ports:
    - "8080:8080"
    env_file:
      - .env
      - recipient_config.env
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ../:/app_root:rw 

    working_dir: /app_root/devops

    command: ["python", "app.py"]
    
    networks: # <--- 2. Assign the service to the network
      - purple_network