version: '3.9'

networks:
  purple_network:
    driver: bridge

services:

  weight-db:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-db
    networks:
      - purple_network

  weight-app:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-app
    networks:
      - purple_network

  billing-db:
    extends:
      file: ../billing/docker-compose.yml
      service: billing-db
    networks:
      - purple_network

  billing:
    extends:
      file: ../billing/docker-compose.yml
      service: billing
    networks:
      - purple_network
