networks:
  purple_network:
    driver: bridge
    external: true

volumes:
  weight_data:
  billing_db_data:

services:

  # ================================
  #           WEIGHT DB (PROD)
  # ================================
  weight-db:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-db

    container_name: weight-db-prod

    networks:
      - purple_network

    environment:
      TZ: Asia/Jerusalem
      MYSQL_ROOT_PASSWORD: ${WEIGHT_MYSQL_ROOT_PASSWORD_PROD}
      MYSQL_DATABASE: ${WEIGHT_MYSQL_DATABASE_PROD}
      DB_PORT: ${WEIGHT_DB_CONTAINER_PORT}

    volumes:
      - ../weight/db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - weight_data:/var/lib/mysql

    ports:
      - "${WEIGHT_DB_HOST_PORT_PROD}:${WEIGHT_DB_CONTAINER_PORT}"

  # ================================
  #           WEIGHT APP (PROD)
  # ================================
  weight-app:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-app

    container_name: weight-app-prod

    networks:
      - purple_network

    environment:
      TZ: Asia/Jerusalem
      DB_USER: ${WEIGHT_DB_USER_PROD}
      DB_PASSWORD: ${WEIGHT_DB_PASSWORD_PROD}
      DB_HOST: ${WEIGHT_DB_HOST_PROD}
      DB_PORT: ${WEIGHT_DB_CONTAINER_PORT}

    ports:
      - "${WEIGHT_APP_HOST_PORT_PROD}:5000"

  # ================================
  #           BILLING DB (PROD)
  # ================================
  billing-db:
    extends:
      file: ../billing/docker-compose.yml
      service: billing-db

    container_name: billing-db-prod

    networks:
      - purple_network

    environment:
      TZ: Asia/Jerusalem
      MYSQL_ROOT_PASSWORD: ${BILLING_MYSQL_ROOT_PASSWORD_PROD}
      MYSQL_DATABASE: ${BILLING_MYSQL_DATABASE_PROD}
      DB_PORT: ${BILLING_DB_PORT_PROD}

    ports:
      - "${BILLING_DB_HOST_PORT_PROD}:${BILLING_DB_PORT_PROD}"

  # ================================
  #           BILLING APP (PROD)
  # ================================
  billing:
    extends:
      file: ../billing/docker-compose.yml
      service: billing

    container_name: billing-app-prod

    networks:
      - purple_network

    environment:
      TZ: Asia/Jerusalem
      DB_USER: ${BILLING_DB_USER_PROD}
      DB_PASSWORD: ${BILLING_DB_PASSWORD_PROD}
      DB_HOST: ${BILLING_DB_HOST_PROD}
      DB_NAME: ${BILLING_DB_NAME_PROD}
      DB_PORT: ${BILLING_DB_PORT_PROD}
      WEIGHT_SERVICE_URL: ${WEIGHT_SERVICE_URL_PROD}
      BILLING_SVC_PORT: ${BILLING_SVC_PORT_PROD}
      RATES_DIR: /app/rates

    ports:
      - "${BILLING_HOST_PORT_PROD}:${BILLING_SVC_PORT_PROD}"
