version: '3.8'

services:
  ci-server:
  #instructs docker compose to build an an image from devops/dockerfile
    build:
      context: .
      dockerfile: dockerfile

    restart: always

    ports:
    - "8080:8080"
    environment:
      # Docker Compose will look for these variables in the host's shell
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    #provision for docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./:/app_root:ro

    working_dir: /app_root

    command: ["python", "app.py"]