
networks:
  purple_network:
    driver: bridge

  billing_network:
    external: true
    name: purple_network

volumes:
  weight_data:
  billing_db_data:

services:

  weight-db:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-db
    env_file:
      - ../weight/.env
    networks:
      - purple_network
    volumes:
      - ../weight/db/weightdb.sql:/docker-entrypoint-initdb.d/weightdb.sql
      - weight_data:/var/lib/mysql
    environment:
      - TZ=Asia/Jerusalem


  # ================================
  #           WEIGHT APP
  # ================================
  weight-app:
    extends:
      file: ../weight/docker-compose.yml
      service: weight-app
    env_file:
      - ../weight/.env
    networks:
      - purple_network
    environment:
      - TZ=Asia/Jerusalem
  # --- BILLING DB ---
  billing-db:
    extends:
      file: ../billing/docker-compose.yml
      service: billing-db
    env_file:
      - ../billing/.env
    networks:
      - purple_network
    environment:
      - TZ=Asia/Jerusalem

  # --- BILLING APP ---
  billing:
    extends:
      file: ../billing/docker-compose.yml
      service: billing
    env_file:
      - ../billing/.env
    networks:
      - purple_network
    environment:
      - TZ=Asia/Jerusalem